Repository chocolat-chaud-io/stator, pull requests merged in 2020-10, with the labels that each got.

#9 Added script to rename project stator to the one desired by the user
  renameProject.js
Labels: enhancement

#10 Added proper readme
  README.md
  package.json
  readmeAssets/projectAppropriationSuccess.png
  readmeAssets/redoc.png
  readmeAssets/todo-demo.gif
  readmeAssets/useTemplate.png
  renameProject.js
Labels: documentation

#14 Added script to enforce naming convetions
  .github/workflows/nx-affected.yml
  README.md
  apps/webapp/src/app/app.tsx
  apps/webapp/src/loading-fab/loading-icon-button.tsx
  apps/webapp/src/redux/root-reducer.ts
  apps/webapp/src/redux/store.ts
  apps/webapp/src/redux/todos/todos.slice.ts
  apps/webapp/src/redux/todos/todos.thunk.ts
  apps/webapp/src/redux/utils/slice-reducer-factory.ts
  apps/webapp/src/redux/utils/slice-state.ts
  apps/webapp/src/redux/utils/thunk-factory.ts
  enforce-file-folder-naming-convention.js
  package.json
  readme-assets/project-appropriation-success.png
  readme-assets/redoc.png
  readme-assets/todo-demo.gif
  readme-assets/use-template.png
  rename-project.js
Labels: documentation, enhancement

#15 Added git hook to validate branch naming convention is respected
  README.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#39 feat: added react eslint rules
  .eslintrc
  README.md
Labels: enhancement

#84 32 add dockerfiles
  .dockerignore
  .github/workflows/build-docker-api.yml
  .github/workflows/build-docker-webapp.yml
  docker-compose.yml
  dockerfiles/api/Dockerfile
  dockerfiles/webapp/Dockerfile
  package.json
  tools/enforce-file-folder-naming-convention.js
Labels: enhancement
